name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/ha-uplink-switcher/ha-uplink-switcher
          npm install
          npm run build

      # Upload build file to the releas as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/ha-uplink-switcher/ha-uplink-switcher/dist/uplink-switcher.js
          asset_name: uplink-switcher.js
          tag: ${{ github.ref }}
          overwrite: true